package tutorials.anirudh.greendaotutorial.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import tutorials.anirudh.greendaotutorial.database.Student;
import tutorials.anirudh.greendaotutorial.database.School;

import tutorials.anirudh.greendaotutorial.database.StudentDao;
import tutorials.anirudh.greendaotutorial.database.SchoolDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig schoolDaoConfig;

    private final StudentDao studentDao;
    private final SchoolDao schoolDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(School.class, schoolDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        schoolDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

}
